//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RyaUploaderV2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RyaUploaderV2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Boiler {
            get {
                object obj = ResourceManager.GetObject("Boiler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succesfully pulled recent matches from CSGO, starting the upload process..
        /// </summary>
        internal static string BoilerSuccess {
            get {
                return ResourceManager.GetString("BoilerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the version of boiler.exe is incorrect.
        /// </summary>
        internal static string DialogBoilerIncorrect {
            get {
                return ResourceManager.GetString("DialogBoilerIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boiler.exe could not be found..
        /// </summary>
        internal static string DialogBoilerNotFound {
            get {
                return ResourceManager.GetString("DialogBoilerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no sharecode available from demo..
        /// </summary>
        internal static string DialogDemoFromShareCodeNotAvailable {
            get {
                return ResourceManager.GetString("DialogDemoFromShareCodeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error occured while retrieving demo data..
        /// </summary>
        internal static string DialogErrorWhileRetrievingDemoData {
            get {
                return ResourceManager.GetString("DialogErrorWhileRetrievingDemoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error occured while retrieving match data..
        /// </summary>
        internal static string DialogErrorWhileRetrievingMatchesData {
            get {
                return ResourceManager.GetString("DialogErrorWhileRetrievingMatchesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid arguments..
        /// </summary>
        internal static string DialogInvalidArguments {
            get {
                return ResourceManager.GetString("DialogInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no new demo has been found..
        /// </summary>
        internal static string DialogNoNewerDemo {
            get {
                return ResourceManager.GetString("DialogNoNewerDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam is restarting..
        /// </summary>
        internal static string DialogRestartSteam {
            get {
                return ResourceManager.GetString("DialogRestartSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam is not running or logged in..
        /// </summary>
        internal static string DialogSteamNotRunningOrNotLoggedIn {
            get {
                return ResourceManager.GetString("DialogSteamNotRunningOrNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libEGL {
            get {
                object obj = ResourceManager.GetObject("libEGL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libGLESv2 {
            get {
                object obj = ResourceManager.GetObject("libGLESv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] msvcp120 {
            get {
                object obj = ResourceManager.GetObject("msvcp120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] msvcr120 {
            get {
                object obj = ResourceManager.GetObject("msvcr120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] protobuf_net {
            get {
                object obj = ResourceManager.GetObject("protobuf_net", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] steam_api {
            get {
                object obj = ResourceManager.GetObject("steam_api", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] steam_appid {
            get {
                object obj = ResourceManager.GetObject("steam_appid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown error..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
